{"name":"Review repository delete review failure","fullName":"TestReviewDeleteSuite/Review repository delete review/TestDelete_Failure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727876946204,"stop":1727876946204,"uuid":"17723186-80c5-11ef-9769-ca15b1947337","historyId":"d27bbb86b5b2b036ca6df7133d207ff2","testCaseId":"2cc7b1565bdd64fe16b6b9e35308b680","labels":[{"name":"language","value":"go1.22.5"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"macbook.local"},{"name":"thread","value":"TestReviewDeleteSuite/Review repository delete review/TestDelete_Failure"},{"name":"suite","value":"Review repository delete review"},{"name":"package","value":"github.com/paw1a/eschool/internal/adapter/repository/postgres/test"}],"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727876946204,"stop":1727876946204,"parameters":[{"name":"Error","value":"sql: connection is already closed: record delete failed"},{"name":"Target","value":"record delete failed"}]}]}