{"name":"User repository find all failure","fullName":"TestUserFindAllSuite/User repository find all/TestFindAll_Failure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727876946211,"stop":1727876946211,"uuid":"177336d0-80c5-11ef-9769-ca15b1947337","historyId":"2f1f80d14e58f2aebc34998f4e50c9a3","testCaseId":"b5aff46d3879fec5f608fa8fbb7e3fbb","labels":[{"name":"language","value":"go1.22.5"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"macbook.local"},{"name":"thread","value":"TestUserFindAllSuite/User repository find all/TestFindAll_Failure"},{"name":"suite","value":"User repository find all"},{"name":"package","value":"github.com/paw1a/eschool/internal/adapter/repository/postgres/test"}],"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727876946211,"stop":1727876946211,"parameters":[{"name":"Error","value":"sql: no rows in result set: record does not exist"},{"name":"Target","value":"record does not exist"}]}]}